apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-dep
  labels:
    k8s-app: basic-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: basic-dep
  template:
    metadata: 
      labels:
        k8s-app: basic-dep
    spec:
      containers:
      - name: basic-dep-pod
        image: ubuntu
        command: ["sh", "-c", "apt update && \
          apt install -y curl && \
          curl -fsSL https://raw.githubusercontent.com/miracleyoo/one-key-linux-setup/master/basic-nopy.sh -o basic-nopy.sh && \
          bash basic-nopy.sh && \
          rm basic-nopy.sh && \
          sleep infinity"]
        resources:
          limits:
            memory: 32Gi
            cpu: 1
            ephemeral-storage: 100Gi
          requests:
            memory: 16Gi
            cpu: 1
            ephemeral-storage: 100Gi        
        volumeMounts:
        - mountPath: /tsukimi
          name: tsukimi
      volumes:
        - name: tsukimi
          persistentVolumeClaim:
            claimName: tsukimi