apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-4gpu
  labels:
    k8s-app: high-4gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: high-4gpu
  template:
    metadata: 
      labels:
        k8s-app: high-4gpu
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
                - NVIDIA-RTX-A5000
                - Quadro-RTX-6000
                - NVIDIA-A10	
                - NVIDIA-TITAN-RTX

      containers:
      - name: high-4gpu
        image: pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel
        command: ["sh", "-c", "apt update && \
          apt install -y curl && \
          curl -fsSL https://raw.githubusercontent.com/miracleyoo/one-key-linux-setup/master/one-key-setup-for-pytorch-docker.sh -o one-key-setup-for-pytorch-docker.sh && \
          bash one-key-setup-for-pytorch-docker.sh && \
          rm one-key-setup-for-pytorch-docker.sh && \
          sleep infinity"]
        resources:
          limits:
            memory: 32Gi
            cpu: 16
            nvidia.com/gpu: 4
            ephemeral-storage: 100Gi
          requests:
            memory: 32Gi
            cpu: 16
            nvidia.com/gpu: 4
            ephemeral-storage: 100Gi        
        volumeMounts:
        - mountPath: /tsukimi
          name: tsukimi
        - mountPath: /hataraku
          name: hataraku
        - mountPath: /dev/shm
          name: cache-volume
      volumes:
        - name: tsukimi
          persistentVolumeClaim:
            claimName: tsukimi
        - name: hataraku
          persistentVolumeClaim:
            claimName: hataraku
        - emptyDir:
            medium: Memory
            sizeLimit: 16Gi
          name: cache-volume